### ISSUE TITLE
Duplicate dependecies on package.json

### ISSUE THREAD

**Issue by itsmvx** [BethelsandoGW/abibas-store#6]
Bang, package json nya duplicate dependencies dari punya ubedz @BethelsandoGW

**Comment by BethelsandoGW** [comment]
duplicate 

    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    
 ini aja kah??

**Comment by BethelsandoGW** [comment]
clear bang @itsmvx

**Comment by BethelsandoGW** [comment]
#8 #7 Done bang
